
// Objective-C API for talking to the following Go packages
//
//	github.com/nomasters/handshake/x/mobile-exp
//
// File is generated by gomobile bind. Do not edit.
#ifndef __HandshakeCore_FRAMEWORK_H__
#define __HandshakeCore_FRAMEWORK_H__

#include "HandshakeCore.objc.h"
#include "Universe.objc.h"

#endif
