// Objective-C API for talking to github.com/nomasters/handshake/x/mobile-exp Go package.
//   gobind -lang=objc github.com/nomasters/handshake/x/mobile-exp
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "Universe.objc.h"


@class MobileCounter;

/**
 * testing out state in the app with a simple counter
 */
@interface MobileCounter : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (long)get;
- (void)inc;
@end

/**
 * testing network communication with a simple interface
and error handling
 */
FOUNDATION_EXPORT NSData* MobileGetHash(NSString* hash, NSError** error);

/**
 * testing interacting with a more complex library
but with a simple func interface
 */
FOUNDATION_EXPORT NSData* MobileGetKey(NSData* pw, NSData* salt);

/**
 * checking out simple string response
 */
FOUNDATION_EXPORT NSString* MobileHelloWorld(void);

FOUNDATION_EXPORT MobileCounter* MobileNewCounter(void);

#endif
